services:
  - type: web
    name: salesbooster-hachedhe
    runtime: node
    rootDir: sales-booster-admin
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
